name: radare2
version: 0.0.0
summary: UNIX-like reverse engineering framework and command-line toolset
description: |
  Radare2 (also known as r2) is a complete framework for reverse-engineering
  and analyzing binaries; composed of a set of small utilities that can be used
  together or independently from the command line. Built around a disassembler
  for computer software which generates assembly language source code from
  machine-executable code, it supports a variety of executable formats for
  different processors and operating systems. Apart from the static analysis
  feature it also supports debugging and emulation. The architecture of the
  framework is modular and allows to use existing or create new plugins for new
  file formats, architectures, analysis features.
license: LGPL-3.0-only
architectures: []
base: core
apps: {}
confinement: classic
grade: stable
environment:
  R2_PREFIX: $SNAP
  PKG_CONFIG_PATH: $SNAP/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
  LD_LIBRARY_PATH: ${SNAP_LIBRARY_PATH}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:$SNAP/lib
  PATH: $SNAP/bin:$PATH
