name: radare2
base: core20
version: '5.8.2'
summary: UNIX-like reverse engineering framework and command-line toolset
description: |
  r2 is a complete rewrite of radare. It provides a set of libraries, tools and
  plugins to ease reverse engineering tasks.

  The radare project started as a simple command-line hexadecimal editor focused
  on forensics. Today, r2 is a featureful low-level command-line tool with
  support for scripting. r2 can edit files on local hard drives, view kernel
  memory, and debug programs locally or via a remote gdb server. r2's wide
  architecture support allows you to analyze, emulate, debug, modify, and
  disassemble any binary.

website: https://www.radare.org/
issues: https://github.com/radareorg/radare2/issues
contact: https://github.com/radareorg/radare2#community
source-code: https://github.com/radareorg/radare2-snap.git
license: LGPL-3.0-only

grade: devel
confinement: strict
compression: xz

plugs:
  home:

apps:
  r2:
    command: bin/r2
  r2agent:
    command: bin/r2agent
  r2p:
    command: bin/r2p
  r2pm:
    command: bin/r2pm
  r2r:
    command: bin/r2r
  rabin2:
    command: bin/rabin2
  radare2:
    command: bin/radare2
  radiff2:
    command: bin/radiff2
  rafind2:
    command: bin/rafind2
  ragg2:
    command: bin/ragg2
  rahash2:
    command: bin/rahash2
  rarun2:
    command: bin/rarun2
  rasign2:
    command: bin/rasign2
  rasm2:
    command: bin/rasm2
  ravc2:
    command: bin/ravc2
  rax2:
    command: bin/rax2

parts:
  radare2:
    plugin: autotools
    source-type: tar
    source: https://github.com/radareorg/radare2/releases/download/5.8.2/radare2-5.8.2.tar.xz
    build-environment:
      - CFLAGS: "$CFLAGS -O3"
    autotools-configure-parameters:
      - --with-checks-level=0
      - --prefix=/usr

