name: Build images
on:
  workflow_call: # called on version update detected
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 
  push:
    branches:
      - 'main'
    paths:
      - 'snap/**'
      - 'docker/**'

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    environment:
      name: snapcraft.io
      url: https://snapcraft.io/radare2
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
          - armhf
          - ppc64el
          - riscv64
          - s390x
    steps:
      # Perform the checkout of the main branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build snap
        id: build
        uses: snapcore/action-build@v1
        with:
          snapcraft-args: --build-for=${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snaps
          path: ${{ steps.build.outputs.snap }}
  
      - name: Publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable

  docker:
    needs:
      - snapcraft
    runs-on: ubuntu-latest
    environment:
      name: docker.io
      url: https://hub.docker.com/r/${{ vars.DOCKERHUB_REPO }}
    steps:
      # Perform the checkout of the main branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Download snap artifacts
        uses: actions/download-artifact@v3
        with:
          name: snaps
          path: '.'

      - name: Map artifacts to docker files
        id: map
        run: .github/scripts/map-docker-files.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: true
          context: docker
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/ppc64le
            linux/s390x
          build-args: |
            BASE_IMAGE=${{ steps.map.outputs.base_image }}
            BASE_SNAP=${{ steps.map.outputs.base_snap }}
            R2_VERSION=${{ steps.map.outputs.r2_version }}
          tags: |
            ${{ vars.DOCKERHUB_REPO }}:latest
            ${{ vars.DOCKERHUB_REPO }}:${{ steps.map.outputs.r2_version }}
