name: Build only
on:
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
          - armhf
          - i386
          - ppc64el
          - riscv64
          - s390x
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # with:
        #   platforms: ${{ matrix.arch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build snap
        run: make snap-buildx SNAP_ARCH=${{ matrix.arch }}

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-${{ matrix.arch }}
          path: snaps/radare2_*.snap
          if-no-files-found: error
          compression-level: 0
  
      - name: Build docker image
        run: make docker-buildx-tarball REGISTRY_IMAGE=localhost/radare2 DOCKER_TAG=gha-${{ github.run_id }} SNAP_ARCH=${{ matrix.arch }}

      - name: Upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-${{ matrix.arch }}
          path: docker-images/radare2-docker-*.tar
          if-no-files-found: error
          compression-level: 6

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Generate SBOM with Syft
        run: syft scan docker:localhost/radare2:gha-${{ github.run_id }} --select-catalogers "+sbom-cataloger" --output spdx-json=docker-${{ matrix.arch }}.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-${{ matrix.arch }}-sbom
          path: docker-${{ matrix.arch }}.spdx.json
