name: Build images
on:
  workflow_call: # called on version update detected
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 
  push:
    branches:
      - 'main'
    paths:
      - 'snap/**'
      - 'alternative/nofrida/snap/**'
      - 'docker/**'

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    environment:
      name: snapcraft.io
      url: https://snapcraft.io/radare2
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - arch: amd64
            path: .
          - arch: arm64
            path: .
        # Issue building frida on armhf (temporally disabled)
          - arch: armhf
            path: alternative/nofrida/
        # platforms without frida supported
          - arch: ppc64el
            path: alternative/nofrida/
          # - arch: riscv64
          #   path: alternative/nofrida/
          # - arch: s390x
          #   path: alternative/nofrida/
    steps:
      # Perform the checkout of the main branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build snap
        id: build
        uses: diddlesnaps/snapcraft-multiarch-action@93ebbb5ce6d1ab2078c201dd38cf1697666404ca
        with:
          architecture: ${{ matrix.cfg.arch }}
          path: ${{ matrix.cfg.path }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snaps
          path: ${{ steps.build.outputs.snap }}
  
      - name: Publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable

  docker:
    needs:
      - snapcraft
    runs-on: ubuntu-latest
    environment:
      name: docker.io
      url: https://hub.docker.com/r/${{ vars.DOCKERHUB_REPO }}
    steps:
      # Perform the checkout of the main branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Download snap artifacts
        uses: actions/download-artifact@v3
        with:
          name: snaps
          path: '.'

      - name: Map artifacts to docker files
        id: map
        run: .github/scripts/map-docker-files.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: true
          context: docker
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/ppc64le
          # linux/riscv64
          # linux/s390x
          build-args: |
            BASE_IMAGE=${{ steps.map.outputs.base_image }}
            R2_VERSION=${{ steps.map.outputs.r2_version }}
          tags: |
            ${{ vars.DOCKERHUB_REPO }}:latest
            ${{ vars.DOCKERHUB_REPO }}:${{ steps.map.outputs.r2_version }}
