name: Build docker
on:
  workflow_call: # called when new snaps has been build
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 
    inputs:
      run_id:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: docker.io
      url: https://hub.docker.com/r/${{ vars.DOCKERHUB_REPO }}
    steps:
      # Perform the checkout of the main branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Download snap artifacts from current run
        if: inputs.run_id == ''
        uses: actions/download-artifact@v3
        with:
          name: snaps
          path: snapcraft
          
      - name: Download snap artifacts from external run
        if: inputs.run_id != ''
        run: gh run download "${{ inputs.run_id }}" --dir snapcraft --name snaps
        env:
          GH_TOKEN: ${{ github.token }}
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fix 5.8.6 tag
        run: docker buildx imagetools create --tag ${{ vars.DOCKERHUB_REPO }}:5.8.6 ${{ vars.DOCKERHUB_REPO }}@sha256:efa4e6ecf8fc55400e08de9d696c5081e86934e360d9025944300c98088f9bd2

      - name: Build and push docker images
        run: scripts/docker-push-multiarch.sh
        env:
          REGISTRY_IMAGE: ${{ vars.DOCKERHUB_REPO }}
