name: Build docker
on:
  workflow_call: # called when new snaps has been build
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 
    inputs:
      run_id:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: docker.io
      url: https://hub.docker.com/r/${{ vars.DOCKERHUB_REPO }}
    steps:
      # Perform the checkout of the main branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Download snap artifacts from current run
        if: inputs.run_id == ''
        uses: actions/download-artifact@v3
        with:
          name: snaps
          path: snapcraft
          
      - name: Download snap artifacts from external run
        if: inputs.run_id != ''
        run: gh run download "${{ inputs.run_id }}" --dir snapcraft --name snaps
        env:
          GH_TOKEN: ${{ github.token }}
  
      - name: Map artifacts to docker files
        id: map
        run: scripts/map-docker-files.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: true
          context: docker
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/ppc64le
          # linux/riscv64
          # linux/s390x
          build-args: |
            BASE_IMAGE=${{ steps.map.outputs.base_image }}
            R2_VERSION=${{ steps.map.outputs.r2_version }}
          tags: |
            ${{ vars.DOCKERHUB_REPO }}:latest
            ${{ vars.DOCKERHUB_REPO }}:${{ steps.map.outputs.r2_version }}
