name: Build snaps
on:
  workflow_call: # called on version update detected
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 
  push:
    branches:
      - 'main'
    paths:
      - 'snapcraft/default/**'
      - 'snapcraft/nofrida/**'
      - 'snapcraft/legacy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: snapcraft.io
      url: https://snapcraft.io/radare2
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - arch: amd64
            type: default
          - arch: arm64
            type: default
        # Issue building frida on armhf (temporally disabled)
          - arch: armhf
            type: nofrida
        # platforms without frida supported
          - arch: ppc64el
            type: nofrida
          # - arch: riscv64
          #   type: nofrida
          # - arch: s390x
          #   type: nofrida
        # legacy platforms
          - arch: i386
            type: legacy
    steps:
      # Perform the checkout of the main branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build snap
        id: build
        uses: diddlesnaps/snapcraft-multiarch-action@93ebbb5ce6d1ab2078c201dd38cf1697666404ca
        with:
          architecture: ${{ matrix.cfg.arch }}
          path: snapcraft/${{ matrix.cfg.type }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snaps
          path: ${{ steps.build.outputs.snap }}
  
      - name: Publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable

  docker:
    needs:
      - build
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
